// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAkgRzVstZZvjlvOR_XJ7rfzbYECmc3gKg',
//     appId: '1:886406325228:web:1e557a757bf5f16b9b16c9',
//     messagingSenderId: '886406325228',
//     projectId: 'wikki-71f80',
//     authDomain: 'wikki-71f80.firebaseapp.com',
//     storageBucket: 'wikki-71f80.firebasestorage.app',
//     measurementId: 'G-16LG7MPPG1',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAhw5lxjd9qb0CDTTfp7DYltOeIs02dcEk',
//     appId: '1:886406325228:android:3836793c98e558e39b16c9',
//     messagingSenderId: '886406325228',
//     projectId: 'wikki-71f80',
//     storageBucket: 'wikki-71f80.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCRoffoABALVcpcYh0H0iHOWFVgnCgyDPQ',
//     appId: '1:886406325228:ios:a5bb4da6ffbdd2279b16c9',
//     messagingSenderId: '886406325228',
//     projectId: 'wikki-71f80',
//     storageBucket: 'wikki-71f80.firebasestorage.app',
//     iosBundleId: 'com.example.wikipideaApplication',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCRoffoABALVcpcYh0H0iHOWFVgnCgyDPQ',
//     appId: '1:886406325228:ios:a5bb4da6ffbdd2279b16c9',
//     messagingSenderId: '886406325228',
//     projectId: 'wikki-71f80',
//     storageBucket: 'wikki-71f80.firebasestorage.app',
//     iosBundleId: 'com.example.wikipideaApplication',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAkgRzVstZZvjlvOR_XJ7rfzbYECmc3gKg',
//     appId: '1:886406325228:web:84cbd64c8f924cb29b16c9',
//     messagingSenderId: '886406325228',
//     projectId: 'wikki-71f80',
//     authDomain: 'wikki-71f80.firebaseapp.com',
//     storageBucket: 'wikki-71f80.firebasestorage.app',
//     measurementId: 'G-QWV7QWPYCV',
//   );
// }
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbFwXZOzFi4Y9DlUIOEAXUNBN2jNY_sGo',
    appId: '1:1007201296541:web:4d71882f97246887793474',
    messagingSenderId: '1007201296541',
    projectId: 'stayon-51caa',
    authDomain: 'stayon-51caa.firebaseapp.com',
    storageBucket: 'stayon-51caa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC61cIsTr8U3VVIsxoXTHl2mbkeJ1BpIiw',
    appId: '1:1007201296541:android:918b07c0655dab4d793474',
    messagingSenderId: '1007201296541',
    projectId: 'stayon-51caa',
    storageBucket: 'stayon-51caa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV8cxR_DOfZR0HOpu89U-W29nRZhVW9PI',
    appId: '1:1007201296541:ios:66a459b9de24fcf7793474',
    messagingSenderId: '1007201296541',
    projectId: 'stayon-51caa',
    storageBucket: 'stayon-51caa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV8cxR_DOfZR0HOpu89U-W29nRZhVW9PI',
    appId: '1:1007201296541:ios:66a459b9de24fcf7793474',
    messagingSenderId: '1007201296541',
    projectId: 'stayon-51caa',
    storageBucket: 'stayon-51caa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbFwXZOzFi4Y9DlUIOEAXUNBN2jNY_sGo',
    appId: '1:1007201296541:web:3a9de1a1c61cef9e793474',
    messagingSenderId: '1007201296541',
    projectId: 'stayon-51caa',
    authDomain: 'stayon-51caa.firebaseapp.com',
    storageBucket: 'stayon-51caa.appspot.com',
  );
}
